cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'caskroom/cask'
tap 'caskroom/versions'
tap 'homebrew/dupes'
tap 'homebrew/versions'

cask 'java'
cask 'xquartz'

brew 'ack'
brew 'archey'
brew 'awscli'
brew 'coreutils'
brew 'dark-mode'
brew 'docker'
brew 'git', args: ['without-completions']
brew 'git-extras'
brew 'git-flow'
brew 'go'
brew 'grc'
brew 'htop-osx'
brew 'hub'
brew 'imagemagick'
brew 'jp2a'
brew 'libcaca', args: ['with-imlib2']
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'readline'
brew 'postgresql'
brew 'ruby-build'
brew 'rbenv'
brew 'roundup'
brew 'rsync'
brew 'spaceman-diff'
brew 'spark'
brew 'ssh-copy-id'
brew 'tree'
brew 'tidy-html5'
brew 'unrar'
brew 'unzip'
brew 'urlview'
brew 'watch'
brew 'webkit2png'
brew 'webp'
brew 'zlib'
brew 'zsh'
brew 'heroku-toolbelt'
brew 'homebrew/dupes/grep'
brew 'wget', args: ['enable-iri']
brew 'youtube-dl'
brew 'vim', args: ['with-lua', 'with-luajit']

cask '1password'
cask 'atom'
cask 'box-sync'
cask 'box-edit'
cask 'cleanmymac'
cask 'coda'
cask 'firefox'
cask 'fluid'
cask 'front'
cask 'google-chrome'
cask 'handbrake'
cask 'imageoptim'
cask 'mapbox-studio'
cask 'opera'
cask 'sequel-pro'
cask 'sketch'
cask 'slack'
cask 'sourcetree'
cask 'sublime-text'
cask 'transmit'
cask 'transmission'
cask 'tunnelbear'
cask 'vagrant'
cask 'vagrant-manager'
cask 'virtualbox'
cask 'vlc'
